services:
  - type: web
    name: paladins-palace
    runtime: node
    region: frankfurt
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    buildCommand: npm ci && npm run vercel-build
    startCommand: npm run start
    healthCheckPath: /
